[versions]
min-sdk = "24"
target-sdk = "36"
compile-sdk = "36"
jvm-target = "21"
desugar = "2.1.5"
agp = "8.13.0"
kotlin = "2.2.20"
core-ktx = "1.17.0"
junit = "4.13.2"
junit-version = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"


[libraries]
androidx-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[bundles]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }