[versions]
# Project
min-sdk = "24"
target-sdk = "36"
compile-sdk = "36"

desugar = "2.1.5"
retrofit = "3.0.0"

[libraries]
androidx-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[bundles]
[plugins]